%% Raw / Denoised / Filtered Trace Viewer
% =========================================================================
%
% Purpose:
%   Check whether stimulation pulses were delivered at the expected timing
%   for the new pulse-train / event-level stimulation design.
%
% Designed for experiment files generated by:
%   design_exp_v4_PulseTrian_4Shank_Flex
% =========================================================================

clear all
addpath(genpath('/Volumes/MACData/Data/Data_Xia/AnalysisFunctions'));

%% ====================== USER SETTINGS ======================

data_folder = '/Volumes/MACData/Data/Data_Xia/DX028/Xia_Elec2_Train2';

% Recording channels to plot, using Depth_s index.
channels_to_plot = 1:2;

% Amplitudes to include.
% [] means all detected real amplitudes.
% Note: zero-current controls are controlled separately by include_zero_control.
amps_to_plot = [10];

% Electrode type for Depth_s mapping:
%   0 = rigid
%   1 = flex
%   2 = 4-shank flex
Electrode_Type = 2;

% Stimulation set selection.
% [] means all detected non-zero StimSetIndex values.
sets_to_plot = [];

% Train/event level selection.
% [] means all detected TrainLevels.
train_levels_to_plot = [];

% Include automatically added simultaneous control?
%   1 = yes
%   0 = no
include_auto_sim = 1;

% Include zero-current baseline control?
% Usually 0, because there should be no stimulation artifact.
include_zero_control = 0;

% Number of raw traces to plot per condition.
nTrials_to_plot = 30;

% Time window around trigger, in ms.
plot_window_ms = [-5 35];

% Trace type:
%   'raw' = amplifier.dat
%   'dn'  = amplifier_dn_sab.dat
%   'mu'  = <base_name>.mu_sab.dat
trace_type = 'raw';

% Y-axis limit.
ylim_raw = [-7000, 7000];

% If 1, print example StimParams rows for selected conditions.
debug_print_trial_content = 1;

% If 1, draw vertical lines at expected stimulation event times.
draw_event_lines = 1;

% If 1, also draw a line at the final expected event time.
% This is useful to see the last stimulation artifact.
draw_final_event_line = 1;

%% ====================== CHECK FOLDER ======================

if ~isfolder(data_folder)
    error('Invalid folder: %s', data_folder);
end

cd(data_folder);

%% ====================== BASE NAME ======================

parts = split(data_folder, filesep);
lastfld = parts{end};
u = strfind(lastfld,'_');

if numel(u) >= 4
    base_name = lastfld(1:u(end-1)-1);
else
    base_name = lastfld;
end

fprintf('\nData folder:\n%s\n', data_folder);
fprintf('Base name: %s\n', base_name);

%% ====================== CHOOSE FILE BY TRACE TYPE ======================

switch trace_type
    case 'raw'
        data_label = 'Raw';
        data_file  = 'amplifier.dat';

    case 'dn'
        data_label = 'Denoised';
        data_file  = 'amplifier_dn_sab.dat';

    case 'mu'
        data_label = 'Filtered';
        data_file  = [base_name '.mu_sab.dat'];

    otherwise
        error('Unknown trace_type "%s". Use ''raw'', ''dn'', or ''mu''.', trace_type);
end

%% ====================== READ INTAN HEADER ======================

fileinfo = dir('info.rhs'); %#ok<NASGU>
[amp_channels, freq_params] = read_Intan_RHS2000_file;

FS = freq_params.amplifier_sample_rate;
nChn = numel(amp_channels);

fprintf('Sampling rate: %.1f Hz\n', FS);
fprintf('Number of amplifier channels: %d\n', nChn);

%% ====================== OPEN DATA FILE ======================

fid = fopen(data_file,'r');

if fid < 0
    error('Cannot open %s', data_file);
end

fprintf('Opened data file: %s\n', data_file);

%% ====================== LOAD TRIGGERS ======================

if isempty(dir('*.trig.dat'))
    cleanTrig_sabquick;
end

trig = loadTrig(0);
nTrig = numel(trig);

fprintf('Number of triggers: %d\n', nTrig);

%% ====================== LOAD EXPERIMENT DATAFILE ======================

fDIR = dir('*_exp_datafile_*.mat');
assert(~isempty(fDIR),'No *_exp_datafile_*.mat found.');

S = load(fDIR(1).name);

StimParams        = S.StimParams;
TrialParams       = S.TrialParams;
simultaneous_stim = S.simultaneous_stim;
n_Trials          = S.n_Trials;
E_MAP             = S.E_MAP; %#ok<NASGU>

if isfield(S, 'StimMeta')
    StimMeta = S.StimMeta;
else
    error('StimMeta was not found in the experiment datafile. This viewer requires the new design code metadata.');
end

if isfield(S, 'trainMode')
    trainMode = S.trainMode;
else
    trainMode = NaN;
end

fprintf('Loaded exp datafile: %s\n', fDIR(1).name);
fprintf('n_Trials from exp file: %d\n', n_Trials);
fprintf('Rows/slots per trial: %d\n', simultaneous_stim);
fprintf('trainMode: %g\n', trainMode);

if n_Trials ~= nTrig
    warning('n_Trials (%d) does not match trigger number (%d). Using min of both for plotting.', ...
        n_Trials, nTrig);
end

nTrials_use = min(n_Trials, nTrig);

%% ====================== REMOVE HEADER ROWS ======================

StimParams_data  = StimParams(2:end,:);
TrialParams_data = TrialParams(2:end,:);

expected_rows = n_Trials * simultaneous_stim;

if size(StimParams_data,1) ~= expected_rows
    warning('StimParams data rows (%d) do not equal n_Trials*simultaneous_stim (%d). Check file.', ...
        size(StimParams_data,1), expected_rows);
end

if size(TrialParams_data,1) ~= expected_rows
    warning('TrialParams data rows (%d) do not equal n_Trials*simultaneous_stim (%d). Check file.', ...
        size(TrialParams_data,1), expected_rows);
end

%% ====================== TRIAL-LEVEL CONDITION IDS ======================
% TrialParams columns from the new design code:
%   column 1 = trial number
%   column 2 = condition ID
%   column 3 = internal electrode ID
%
% Because each trial has "simultaneous_stim" rows, we use the first row of
% each trial to get the trial-level condition ID.

firstRow_eachTrial = 1:simultaneous_stim:size(TrialParams_data,1);

trialNumber_trial = cell2mat(TrialParams_data(firstRow_eachTrial,1)); %#ok<NASGU>
conditionID_trial = cell2mat(TrialParams_data(firstRow_eachTrial,2));

if numel(conditionID_trial) ~= n_Trials
    warning('Number of trial-level condition IDs does not match n_Trials.');
end

%% ====================== BUILD TRIAL METADATA FROM StimMeta ======================
% For timing, amplitude, train level, and set information, we use StimMeta.
%
% But for the displayed stimulation channel label, we do NOT use StimMeta.CHN.
% The title label is built later from actual StimParams column 1.

stimSet_trial      = NaN(n_Trials,1);
trainLevel_trial   = NaN(n_Trials,1);
totalLevels_trial  = NaN(n_Trials,1);
amp_trial          = NaN(n_Trials,1);
isAutoSim_trial    = false(n_Trials,1);
isZero_trial       = false(n_Trials,1);
eventEnd_ms_trial  = NaN(n_Trials,1);

eventTimes_ms_trial = cell(n_Trials,1);
pulseCount_trial    = cell(n_Trials,1);
stimCHN_trial       = cell(n_Trials,1); % StimMeta CHN, only for debug comparison
ptd_ms_trial        = cell(n_Trials,1);

for tr = 1:n_Trials

    condID = conditionID_trial(tr);

    if condID < 1 || condID > numel(StimMeta)
        warning('Trial %d has invalid condition ID %d.', tr, condID);
        continue;
    end

    meta = StimMeta(condID);

    if isfield(meta, 'StimSetIndex')
        stimSet_trial(tr) = meta.StimSetIndex;
    end

    if isfield(meta, 'TrainLevel')
        trainLevel_trial(tr) = meta.TrainLevel;
    end

    if isfield(meta, 'TotalTrainLevels')
        totalLevels_trial(tr) = meta.TotalTrainLevels;
    end

    if isfield(meta, 'Amp_uA')
        amp_vec = meta.Amp_uA;
        amp_vec = amp_vec(:)';

        % For normal stimulation, all active electrodes usually share the
        % same amplitude. For display/filtering, use the max positive amp.
        if all(amp_vec <= 0)
            amp_trial(tr) = 0;
        else
            amp_trial(tr) = max(amp_vec(amp_vec > 0));
        end
    end

    if isfield(meta, 'IsAutoSimultaneous')
        isAutoSim_trial(tr) = logical(meta.IsAutoSimultaneous);
    end

    if isfield(meta, 'IsZeroCurrentControl')
        isZero_trial(tr) = logical(meta.IsZeroCurrentControl);
    end

    if isfield(meta, 'EventTimesIncluded_ms')
        eventTimes_ms_trial{tr} = meta.EventTimesIncluded_ms;
    else
        eventTimes_ms_trial{tr} = [];
    end

    if isfield(meta, 'EventEndTime_ms')
        eventEnd_ms_trial(tr) = meta.EventEndTime_ms;
    end

    if isfield(meta, 'PulseCountPerElectrode')
        pulseCount_trial{tr} = meta.PulseCountPerElectrode;
    else
        pulseCount_trial{tr} = [];
    end

    if isfield(meta, 'CHN')
        stimCHN_trial{tr} = meta.CHN;
    else
        stimCHN_trial{tr} = [];
    end

    if isfield(meta, 'PTD_ms')
        ptd_ms_trial{tr} = meta.PTD_ms;
    else
        ptd_ms_trial{tr} = [];
    end
end

%% ====================== APPLY USER FILTERS ======================

% Amplitude selection.
detected_amps = unique(amp_trial(~isnan(amp_trial)));

if include_zero_control == 0
    detected_amps = detected_amps(detected_amps > 0);
end

if isempty(amps_to_plot)
    amps_sel = detected_amps;
else
    amps_sel = intersect(detected_amps, amps_to_plot);
end

% Stimulation set selection.
detected_sets = unique(stimSet_trial(~isnan(stimSet_trial)));

if include_zero_control == 0
    detected_sets = detected_sets(detected_sets > 0);
end

if isempty(sets_to_plot)
    set_sel = detected_sets;
else
    set_sel = intersect(detected_sets, sets_to_plot);
end

% Train level selection.
detected_train_levels = unique(trainLevel_trial(~isnan(trainLevel_trial)));

if isempty(train_levels_to_plot)
    train_levels_sel = detected_train_levels;
else
    train_levels_sel = intersect(detected_train_levels, train_levels_to_plot);
end

fprintf('\nDetected amplitudes: ');
disp(detected_amps');

fprintf('Selected amplitudes: ');
disp(amps_sel');

fprintf('\nDetected StimSetIndex values: ');
disp(detected_sets');

fprintf('Selected StimSetIndex values: ');
disp(set_sel');

fprintf('\nDetected TrainLevels: ');
disp(detected_train_levels');

fprintf('Selected TrainLevels: ');
disp(train_levels_sel');

fprintf('\nDetected event end times (ms): ');
disp(unique(eventEnd_ms_trial(~isnan(eventEnd_ms_trial)))');

%% ====================== DEBUG TRIAL CONTENT CHECK ======================
% Print one example trial for each selected set/amplitude/train level.
%
% This section is useful for checking:
%   1) actual StimParams CHANNEL names
%   2) internal TrialParams electrode IDs
%   3) StimMeta CHN
%
% After changeelectrode, StimParams CHANNEL is the most important one.

if debug_print_trial_content == 1

    fprintf('\n================ DEBUG EVENT-TRAIN TRIAL CONTENT CHECK ================\n');

    for i_set = 1:numel(set_sel)

        set_id = set_sel(i_set);

        for i_amp = 1:numel(amps_sel)

            amp_val = amps_sel(i_amp);

            for i_level = 1:numel(train_levels_sel)

                level_val = train_levels_sel(i_level);

                tr_debug = find(stimSet_trial == set_id & ...
                                amp_trial == amp_val & ...
                                trainLevel_trial == level_val & ...
                                isZero_trial == 0, ...
                                1, 'first');

                if isempty(tr_debug)
                    continue;
                end

                condID_debug = conditionID_trial(tr_debug);
                meta_debug = StimMeta(condID_debug);

                rr = (tr_debug-1)*simultaneous_stim + (1:simultaneous_stim);

                stimNames_debug   = StimParams_data(rr,1);
                ptd_debug         = cell2mat(StimParams_data(rr,6));
                pulseNum_debug    = cell2mat(StimParams_data(rr,8));
                pulsePeriod_debug = cell2mat(StimParams_data(rr,9));
                amp_debug         = cell2mat(StimParams_data(rr,16));
                chn_debug         = cell2mat(TrialParams_data(rr,3));

                activeRows_debug = amp_debug > 0;

                fprintf('\nSet %g | Amp %.1f uA | TrainLevel %g | Trial %d | CondID %d\n', ...
                    set_id, amp_val, level_val, tr_debug, condID_debug);

                fprintf('  IsAutoSimultaneous: %d\n', isAutoSim_trial(tr_debug));

                fprintf('  Actual active StimParams CHANNEL:   ');
                disp(stimNames_debug(activeRows_debug)');

                fprintf('  Internal TrialParams electrode ID:  ');
                disp(chn_debug(activeRows_debug)');

                fprintf('  StimMeta CHN:                       ');
                disp(stimCHN_trial{tr_debug});

                fprintf('  PTD_ms from StimMeta:               ');
                disp(ptd_ms_trial{tr_debug});

                fprintf('  PulseCountPerElectrode:             ');
                disp(pulseCount_trial{tr_debug});

                fprintf('  EventTimesIncluded_ms:              ');
                disp(eventTimes_ms_trial{tr_debug});

                fprintf('  EventEndTime_ms:                    %.3f\n', eventEnd_ms_trial(tr_debug));

                fprintf('  All StimParams row names:           ');
                disp(stimNames_debug');

                fprintf('  All TrialParams electrode IDs:      ');
                disp(chn_debug');

                fprintf('  StimParams PTD_us:                  ');
                disp(ptd_debug');

                fprintf('  StimParams PulseNum:                ');
                disp(pulseNum_debug');

                fprintf('  StimParams PulsePeriod:             ');
                disp(pulsePeriod_debug');

                fprintf('  StimParams Amp_col16:               ');
                disp(amp_debug');

                % Optional consistency check:
                % Reconstruct actual active event times directly from StimParams.
                eventTimes_fromRows_us = [];

                for rridx = find(activeRows_debug(:))'
                    eventTimes_fromRows_us = [eventTimes_fromRows_us, ...
                        ptd_debug(rridx) + (0:pulseNum_debug(rridx)-1) * pulsePeriod_debug(rridx)];
                end

                eventTimes_fromRows_ms = unique(sort(eventTimes_fromRows_us)) ./ 1000;

                fprintf('  Recomputed events from active StimParams rows (ms): ');
                disp(eventTimes_fromRows_ms);

                if isfield(meta_debug, 'EventTimesIncluded_ms')
                    metaEvents = meta_debug.EventTimesIncluded_ms;
                    if numel(metaEvents) == numel(eventTimes_fromRows_ms) && ...
                            all(abs(metaEvents(:)' - eventTimes_fromRows_ms(:)') < 1e-6)
                        fprintf('  Event timing check: OK\n');
                    else
                        fprintf('  Event timing check: WARNING, StimMeta and StimParams-derived events differ.\n');
                    end
                end
            end
        end
    end

    fprintf('=======================================================================\n');
end

%% ====================== TIME SAMPLES ======================

samp_win = round(plot_window_ms/1000 * FS);
Nsamp = samp_win(2)-samp_win(1)+1;
time_ms = (samp_win(1):samp_win(2)) / FS * 1000;

%% ====================== CHANNEL MAP ======================

d = Depth_s(Electrode_Type);

%% ====================== MAIN LOOP ======================
% Plot structure:
%   one figure = recording channel × stimulation set × amplitude
%   subplots   = train/event levels

for ich = 1:length(channels_to_plot)

    ch_plot  = channels_to_plot(ich);
    ch_intan = d(ch_plot);

    if ch_intan > nChn
        warning('Channel %d maps to Intan channel %d, larger than nChn=%d. Skipped.', ...
                ch_plot, ch_intan, nChn);
        continue;
    end

    for i_set = 1:length(set_sel)

        set_id = set_sel(i_set);

        for i_amp = 1:length(amps_sel)

            amp_val = amps_sel(i_amp);

            %% ----- Build set label from actual StimParams CHANNEL names -----
            % This is the key corrected section.
            %
            % The actual stimulation channel name is in:
            %
            %       StimParams_data(:,1)
            %
            % Example:
            %       'A-017'
            %       'A-016'
            %
            % Active rows are identified by:
            %
            %       StimParams_data(:,16) > 0
            %
            % We do NOT use StimMeta.CHN here, because StimMeta may not have
            % been updated after changeelectrode.

            tr_set_label = find(stimSet_trial == set_id & ...
                                amp_trial == amp_val & ...
                                isZero_trial == 0, ...
                                1, 'first');

            if include_auto_sim == 0 && ~isempty(tr_set_label) && isAutoSim_trial(tr_set_label)
                tr_set_label = find(stimSet_trial == set_id & ...
                                    amp_trial == amp_val & ...
                                    isZero_trial == 0 & ...
                                    isAutoSim_trial == 0, ...
                                    1, 'first');
            end

            if ~isempty(tr_set_label)

                rr_label = (tr_set_label-1)*simultaneous_stim + (1:simultaneous_stim);

                stimNames_all = StimParams_data(rr_label,1);
                ampVec_actual = cell2mat(StimParams_data(rr_label,16));

                activeRows_label = ampVec_actual > 0;

                stimNames_active = stimNames_all(activeRows_label);

                if isempty(stimNames_active)
                    set_label = sprintf('Set%d', set_id);
                else
                    % Remove duplicate labels while keeping the original order.
                    % For most two-electrode conditions this should remain:
                    %   {'A-017','A-016'}
                    stimNames_active = unique(stimNames_active, 'stable');

                    if isAutoSim_trial(tr_set_label)
                        set_label = ['AutoSim: ' strjoin(stimNames_active', '+')];
                    else
                        set_label = strjoin(stimNames_active', '→');
                    end
                end

            else
                set_label = sprintf('Set%d', set_id);
            end

            %% ----- Decide subplot list -----
            subplot_levels = train_levels_sel;

            % Remove train levels that do not exist for this set/amp.
            hasLevel = false(size(subplot_levels));

            for ii = 1:numel(subplot_levels)
                thisLevel = subplot_levels(ii);

                tlist_check = find(stimSet_trial == set_id & ...
                                   amp_trial == amp_val & ...
                                   trainLevel_trial == thisLevel & ...
                                   isZero_trial == 0);

                if include_auto_sim == 0
                    tlist_check = tlist_check(isAutoSim_trial(tlist_check) == 0);
                end

                if ~isempty(tlist_check)
                    hasLevel(ii) = true;
                end
            end

            subplot_levels = subplot_levels(hasLevel);

            nSub = length(subplot_levels);

            if nSub == 0
                continue;
            end

            nRows = ceil(sqrt(nSub));
            nCols = ceil(nSub / nRows);

            %% ----- Create figure -----
            figName = sprintf('%sTrace_Ch%d_Set%g_Amp%g_EventTrain', ...
                              data_label, ch_plot, set_id, amp_val);

            figure('Name',figName,'Color','w','Position',[150 150 1500 850]);

            %% ----- Subplot loop -----
            for i_sub = 1:nSub

                level_val = subplot_levels(i_sub);

                tlist = find(stimSet_trial == set_id & ...
                             amp_trial == amp_val & ...
                             trainLevel_trial == level_val & ...
                             isZero_trial == 0);

                if include_auto_sim == 0
                    tlist = tlist(isAutoSim_trial(tlist) == 0);
                end

                % Keep only trials that have triggers.
                tlist = tlist(tlist <= nTrials_use);

                subplot(nRows, nCols, i_sub);
                hold on;

                if isempty(tlist)
                    title(sprintf('TrainLevel %g\nNo trials', level_val), 'Interpreter','none');

                    % Use plot instead of xline to avoid MATLAB graphics
                    % "internal" field error on some versions.
                    plot([0 0], ylim_raw, 'r--');

                    xlabel('Time (ms)');
                    ylabel('uV');
                    ylim(ylim_raw);
                    xlim(plot_window_ms);
                    continue;
                end

                % Use first matching trial to get display metadata.
                tr_example = tlist(1);

                eventTimes_ms = eventTimes_ms_trial{tr_example};
                eventEnd_ms   = eventEnd_ms_trial(tr_example);
                pulseCounts   = pulseCount_trial{tr_example};
                totalLevels   = totalLevels_trial(tr_example);

                if isempty(eventTimes_ms)
                    eventText = '[]';
                else
                    eventText = num2str(eventTimes_ms);
                end

                if isempty(pulseCounts)
                    pulseText = '[]';
                else
                    pulseText = num2str(pulseCounts);
                end

                title_text = sprintf('Level %g/%g | pulses [%s] | events [%s] ms', ...
                    level_val, totalLevels, pulseText, eventText);

                % Only draw first N trials to avoid overcrowding.
                tlist_plot = tlist(1:min(nTrials_to_plot, numel(tlist)));

                %% ----- Plot trial traces -----
                nPlotted = 0;

                for k = 1:numel(tlist_plot)

                    tr = tlist_plot(k);

                    if tr > length(trig)
                        continue;
                    end

                    start_idx = trig(tr) + samp_win(1);

                    % Skip if the requested window starts before file beginning.
                    if start_idx < 0
                        continue;
                    end

                    byte_pos = start_idx * nChn * 2;

                    fseek(fid, byte_pos, 'bof');
                    data_block = fread(fid, [nChn, Nsamp], 'int16') * 0.195;

                    % Skip incomplete reads near the end of file.
                    if size(data_block,2) < Nsamp
                        continue;
                    end

                    plot(time_ms, data_block(ch_intan,:), 'LineWidth', 1);
                    nPlotted = nPlotted + 1;
                end

                %% ----- Draw expected stimulation event lines -----
                % Use normal plot lines instead of xline.
                % This avoids the MATLAB "Unrecognized field name internal"
                % error that can happen with xline in some graphics versions.

                plot([0 0], ylim_raw, 'r--', 'LineWidth', 1);

                if draw_event_lines == 1 && ~isempty(eventTimes_ms)
                    for ee = 1:numel(eventTimes_ms)

                        thisEvent = eventTimes_ms(ee);

                        % Avoid drawing a second black line exactly on top
                        % of the red trigger line at 0 ms.
                        if abs(thisEvent) < 1e-9
                            continue;
                        end

                        plot([thisEvent thisEvent], ylim_raw, 'k--', 'LineWidth', 1);
                    end
                end

                if draw_final_event_line == 1 && isfinite(eventEnd_ms) && eventEnd_ms > 0
                    plot([eventEnd_ms eventEnd_ms], ylim_raw, 'b:', 'LineWidth', 1.5);
                end

                %% ----- Axis formatting -----
                xlabel('Time (ms)');
                ylabel('uV');
                ylim(ylim_raw);
                xlim(plot_window_ms);

                title(sprintf('%s\n%d trials plotted', title_text, nPlotted), ...
                      'Interpreter','none');

            end % subplot loop

            %% ----- Figure title -----
            sgtitle(sprintf('%s Trace | Rec Ch %d | Set %g: %s | %g uA | trainMode %g', ...
                data_label, ch_plot, set_id, set_label, amp_val, trainMode), ...
                'Interpreter','none');

        end % amplitude
    end % set
end % channel

fclose(fid);

fprintf('\nFinished plotting event-level pulse-train raw traces.\n');